# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.PositiveIntegerField(unique=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=12, null=True)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=44)),
            ],
        ),
        migrations.CreateModel(
            name='Non_IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='Non_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera', to='CAM2API.Non_IP'),
        ),
        migrations.AddField(
            model_name='camera',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera', to='CAM2API.IP'),
        ),
    ]
