# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 22:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.PositiveIntegerField(unique=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=12, null=True)),
                ('country', models.CharField(max_length=50)),
                ('lat_lng', django.contrib.gis.db.models.fields.GeometryField(default=0, geography=True, srid=4326)),
                ('source', models.CharField(max_length=30)),
                ('source_url', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField()),
                ('camera_type', models.CharField(choices=[(0, 'Non_IP'), (1, 'IP')], default='Non_IP', max_length=10)),
                ('description', models.CharField(max_length=100, null=True)),
                ('is_video', models.BooleanField()),
                ('framerate', models.FloatField(max_length=100, null=True)),
                ('outdoors', models.NullBooleanField()),
                ('indoors', models.NullBooleanField()),
                ('traffic', models.NullBooleanField()),
                ('inactive', models.NullBooleanField()),
                ('resolution_w', models.PositiveIntegerField(null=True)),
                ('resolution_h', models.PositiveIntegerField(null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=44)),
                ('port', models.PositiveIntegerField(null=True)),
                ('brand', models.PositiveIntegerField(null=True)),
                ('model', models.PositiveIntegerField(null=True)),
                ('video_path', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=100)),
                ('rtsp_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Non_IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
