# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=12)),
                ('country', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=30)),
                ('source_url', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField()),
                ('description', models.CharField(max_length=100, null=True)),
                ('is_video', models.BooleanField()),
                ('framerate', models.FloatField(max_length=100, null=True)),
                ('outdoors', models.NullBooleanField()),
                ('indoors', models.NullBooleanField()),
                ('traffic', models.NullBooleanField()),
                ('inactive', models.NullBooleanField()),
                ('resolution_w', models.PositiveIntegerField(null=True)),
                ('resolution_h', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
