# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAM2API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='state',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
