# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAM2API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='lat_lng',
        ),
        migrations.AddField(
            model_name='camera',
            name='float_lat',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='float_lng',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
