# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 17:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAM2API', '0002_auto_20170518_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='lat_lng',
            field=django.contrib.gis.db.models.fields.GeometryField(default=0, geography=True, srid=4326),
        ),
    ]
