# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAM2API', '0003_camera_lat_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='float_lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='float_lng',
            new_name='lng',
        ),
    ]
