# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAM2API', '0005_token_access_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='permission',
            field=models.CharField(default='BaseUser', max_length=20, verbose_name='Permission'),
        ),
    ]
